workflows:
  android-apk:
    name: Android APK Release
    environment:
      flutter: stable
    scripts:
      - name: Prepare Flutter project
        script: |
          flutter create --platforms=android --org com.mustans.holo360app .
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/flutter-apk/*.apk
