name: mustans_holo_360
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  image: ^4.2.0
  path_provider: ^2.1.4
  gal: ^2.3.0
  ffmpeg_kit_flutter_min_gpl: ^6.0.3

flutter:
  uses-material-design: true
